# Use an official Python runtime as a parent image
FROM python:3.8-slim
# Set the working directory in the container
WORKDIR /usr/src/app
# Copy the current directory contents into the container at /usr/src/app
COPY test.py .
# Make port 1500 available to the world outside this container
EXPOSE 1500
# Define environment variable
ENV NAME World
# Run app.py when the container launches
CMD ["python", "test.py"]
