version: '3'
services:
  deploy:
    container_name: retr0GPT
    restart: unless-stopped
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
      - "6000:5000"
    privileged: true 
