version: '3'
services:
  challenge:
    container_name: recursed
    restart: unless-stopped
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
      - "1515:5000"
    environment:
      FLAG: "Securinets{CL0S3_TH3_D00R_N3XT_TIME!}"
 