version: '3'
services:
  deploy:
    container_name: marketManager
    restart: unless-stopped
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
      - "6300:5000"
    privileged: true 
