version: '3'
services:
  challenge:
    container_name: lee-sin
    restart: unless-stopped
    build:
      context: ./challenge
      dockerfile: Dockerfile
    environment:
      FLAG: "Securinets{i_see_all!}"
 